### ISSUE TITLE
error related to curl

### ISSUE THREAD

**Issue by mattos123** [slawkens/myaac-gesior-shop-system#6]
```
CURL can't connect: Protocol "https" not supported or disabled in libcurl


Backtrace:

#0 /var/www/system/libs/PagSeguroLibrary/utils/PagSeguroHttpConnection.class.php(59): PagSeguroHttpConnection->curlConnection('POST', 'https://ws.pags...', 20, 'UTF-8', Array)
#1 /var/www/system/libs/PagSeguroLibrary/service/PagSeguroPaymentService.class.php(78): PagSeguroHttpConnection->post('https://ws.pags...', Array, 20, 'UTF-8')
#2 /var/www/system/libs/PagSeguroLibrary/domain/PagSeguroPaymentRequest.class.php(627): PagSeguroPaymentService::createCheckoutRequest(Object(PagSeguroAccountCredentials), Object(PagSeguroPaymentRequest), false)
#3 /var/www/system/payments/pagseguro_redirect.php(38): PagSeguroPaymentRequest->register(Object(PagSeguroAccountCredentials))
#4 /var/www/system/pages/points.php(69): require('/var/www/system...')
#5 /var/www/index.php(400): require('/var/www/system...')
#6 {main}

```

ubuntu 16.04
curl installed
openssl installed

**Comment by slawkens** [comment]
This is problem with your distro.

Not related to this plugin, so I'm closing it now.
